databases:
  - name: joestar-api
    databaseName: joestar-api
    user: joestar-api

services:
  - type: web
    name: joestar-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: joestar-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
